# ESCREVA UM PROGRAMA QUE PERGUNTE A QUANTIDADE DE KM PERCORRIDOS POR UM CARRO ALUGADO E A QUANTIDADE DE DIAS PELOAS QUAIS ELE FOI ALUGADO
# CALCULE O PREÇO A PAGAR SABENDO QUE O CARRO CUSTA R$ 60,00 POR DIA E O KM RODADO É DE 0,15 CENTAVOS
