# FAÇA UM PROGRAMA QUE LEIA O ANO DE NASCIMENTO DE UM JOVEM E INFORMA DE ACORDO COM SUA IDADE 
# SE ELE AINDA VAI SE ALISTAR
# SE JÁ ESTA NA HORA DELE SE ALISTAR
# SE JÁ PASSOU DO TEMPO DO ALISTAMENTO
# O PROGRAMA AINDA DEVERA MOSTRAR QUANTO TEMPO FALTA OU PASSOU DA DATA DE ALISTAMENTO