# ESCREVA UM PROGRAMA QUE LEIA DOIS NUMEROS INTEIROS E COMPARE-OS  MOSTRANDO NA TELA UMA DAS SEGUINTES MENSAGEM. 
# O PRIMEIRO VALOR É MAIOR
# O SEGUNDO VALOR É MAIOR
# NÃO EXISTE VALOR MAIOR, OS NUMEROS SÃO IGUAIS