# CRIE UM PROGRAMA QUE LEIA DUAS NOTAS DE UM ALUNO E CALCULE A MEDIA MOSTRANDO A SEGUINTE MENSAGEM NO FINAL
# MÉDIA ABAIXO DE 5.0 REPROVADO
# MÉDIA ENTRE 5.0 E 6.9 RECUPERAÇÃO
# MEDIA ACIMA DE 7.0 APROVADO