# A CONFEDERAÇÃO NACIONAL DE NATAÇÃO PRECISA DE UM PROGRAMA QUE LEIA O ANO DE NASCIMENTO DE UM ATLETA E MOSTRE SUA CATEGORIA POR IDADE
# ATÉ 9 ANOS MIRIM
# ATÉ 14 ANOS INFANTIL
# ATÉ 19 ANOS JUNIOR
# ATÉ 20 SENIOR
# ACIMA MASTER

