# ELABORE UM PROGRAMA QUE CALCULE O VALOR A SER PAGO POR UM PRODUTO CONSIDERANDO O SEU PREÇO NORMAL E CONDIÇÃO DE PAGAMENTO
# A VISTA DINHEIRO OU CHEQUE 10% DE DESCONTO
# A VISTA NO CARTÃO 5% DE DESCONTO
# EM DUAS VEZES NO CARTÃO PREÇO NORMAL
# 3X OU MAIS NO CARTÃO 20% DE JUROS